language: node_js
    - "8"
notifications:
  email: false
install: 
    - npm install 
services: 
    - postgresql 
script: npm run test:all
before_script:
    - psql -c 'drop database if exists events_manager_test;' -U postgres
    - psql -c 'CREATE DATABASE events_manager_test;' -U postgres
    - npm install nyc coveralls codecov codeclimate-test-reporter -g
after_script: 
    - nyc report --reporter=text-lcov | coveralls
    - codeclimate-test-reporter < ./coverage/lcov.info
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT