language: node_js
    - "6"
notifications:
  email: false
install: 
    - npm install 
services: 
    - postgresql 
cache: 
    directories: 
        - "node_modules"
script: npm run test
before_script:
    - psql -c 'drop database if exists events_manager_test;' -U postgres
    - psql -c 'CREATE DATABASE events_manager_test;' -U postgres
    - npm install -nyc
after_script: 
    - nyc report --reporter=text-lcov | coveralls