version: '3.8'

services:
    web:
        build: .
        ports:
            -'3000:3000'
    db:
        image: 'postgres'
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - '4321:5432'
        environment: 
            - POSTGRES_PASSWORD= 'postgres'
            - POSTGRES_DB= 'Events'
        