apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  labels:
    name: "{{ .Values.name }}"
    app: "{{ .Values.name }}"
spec:
  replicas: 2
  selector:
    matchLabels:
      name: "{{ .Values.name }}"
      app: "{{ .Values.name }}"

  template:
    metadata:
      name: "{{ .Values.name }}"
      labels:
        name: "{{ .Values.name }}"
        app: "{{ .Values.name }}"
    spec:
      containers:
      - name: "{{ .Values.name }}"
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 8080